name       : libde265
version    : 1.0.6
release    : 3
source     :
    - https://github.com/strukturag/libde265/releases/download/v1.0.6/libde265-1.0.6.tar.gz : e2a34ca3934a826d0893e966ee93bc2d207f505253be94ad38fb40ca98cceb5f
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : An open h.265 video codec implementation
description: |
    libde265 is an open source implementation of the h.265 video codec. It is written from scratch and has a plain C API to enable a simple integration into other software.

    libde265 supports WPP and tile-based multithreading and includes SSE optimizations. The decoder includes all features of the Main profile and correctly decodes almost all conformance streams.
setup      : |
    # disable dec265 & sherlock265 examples so we don't need any build dependencies
    # Add a prefix because one of the binaries is named 'tests', duh !
    %configure --disable-static \
        --disable-dec265 \
        --disable-sherlock265 \
        --program-prefix=de265-
build      : |
    %make
install    : |
    %make_install
